config/routes.rb
SparkleWeb::Application.routes.draw do

  root 'lights#index'
  resources :lights

  

end

app/models/light.rb
class Light < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lights_controller.rb
class LightsController < ApplicationController

  def index 
    @lights = Light.all
    respond_to do |format|
      format.html # index.html.haml
      format.json { render json: @lights}
    end
  end

  def new
    @light = Light.new
  end

  def show
    @light = Light.find(params[:id])
    respond_to do |format| 
      format.html { render :layout => "mobile" }
      format.json { render :json => @light } 
    end
  end

  # POST /lights
  # POST /lights.json
  def create
    @light = Light.new(light_params)

    respond_to do |format|
      if @light.save
        format.html { redirect_to lights_path, notice: 'Light was successfully created.' }
        format.json { render action: 'show', status: :created, location: @light }
      else
        format.html { render action: 'new' }
        format.json { render json: @light.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lights/1
  # DELETE /lights/1.json
  def destroy
    @light = Light.find(params[:id])
    @light.destroy
    respond_to do |format|
      format.html { redirect_to lights_url }
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /lights/1
  # PATCH/PUT /lights/1.json
  def update
    @light = Light.find(params[:id])
    respond_to do |format|
      if @tile.update(tile_params)
        format.html { redirect_to @tile, notice: 'Tile was successfully updated.' }
        format.json { render nothing: true, status: 204 }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tile.errors, status: :unprocessable_entity }
      end
    end
  end



  private
    def light_params
      params.require(:light).permit( :name, :lit)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SparkleWeb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/mobile.html.haml
!!! 5

%html{"ng-app" => "sparkleApp"}
  %head
    %title SparkleWeb
    = stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track" => true
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body.body
    -if notice.present?
      %p.notice= notice 
    - if alert.present?
      %p.alert.alert-info= alert 
    = yield

app/views/lights/_form.html.haml
= simple_form_for @light, :html => {:multiplart => true} do |f|
  - if @light.errors.any?
    #error_explanation
      %h2= "#{pluralize(@light.errors.count, "error")} prohibited this light from being saved:"
      %ul
        - @light.errors.full_messages.each do |msg|
          %li= msg
  = f.input :name
  .actions
    = f.submit 'Save', :class => 'btn btn-success'

app/views/lights/index.html.haml
%h1 Lights

- if @lights.present?
  -@lights.each do |light|
    %p
      = link_to light.name, light_path(light)      
      - if light.lit
        ON
      - else 
        OFF
      = link_to 'Edit', edit_light_path(light), :class => 'btn btn-primary btn-xs'
      = link_to 'Destroy', light, :method => :delete, :data => { :confirm => 'Are you sure?' },:class => 'btn btn-danger btn-xs'

- else 
  %p No lights currently available. 


= link_to 'New Light', new_light_path

app/views/lights/new.html.haml
%h1 New Light

= render 'form'

= link_to 'See all lights', lights_path

app/views/lights/show.html.haml
.show{"ng-controller" => "LightsCtrl"}
  .name
    %h1= @light.name

  .state
    {{ lit }}
    %br
    %a{"ng-click" => "on_switch()"}
      ON
    %a{"ng-click" => "off_switch()"}
      OFF

    / - if @light.lit
    /   ON | 
    /   %a{"ng-click" => "off_switch()"}
    /     OFF
    / - else 
    /   %a{"ng-click" => "on_switch()"}
    /     ON
    /   | OFF

  / = link_to 'See all lights', lights_path